### ISSUE TITLE
Request/Idea: Add additional connector to receiving side of Node

### ISSUE THREAD

**Issue by Dunnenj** [hj91/node-red-contrib-energy-meter#1]
Is it possible to add an additional connector to the receiving side of the Node. The advantage of this would be that the number of Modbus Nodes could be limited.

**Comment by hj91** [comment]
Can you elaborate it more specifically ?

**Comment by Dunnenj** [comment]
Hope this helps. 

What I want to achieve is retrieving the info with the Modbus Node. The next step will be a split of the array into messages (as shown below). Preferably I will connect these (two) messages to the energy meter Node 

![image](https://github.com/hj91/node-red-contrib-energy-meter/assets/67200790/4943a543-b537-4084-9ac8-580ab0aebd29)

Currently I have the setup as below. But that means that for each parameter that I want to receive I need to use a Modbus Node.

![image](https://github.com/hj91/node-red-contrib-energy-meter/assets/67200790/fc78aac3-720b-4984-921b-78e1bd30db11)

**Comment by hj91** [comment]
By design this node works properly but I will suggest you to create an array of all modbus outputs and then using a simple function, pass on msg.payload[0], msg.payload[1]...msg.payload[n] to this node..

So basically you will be using one single modbus read node and distribute the array output to energy-meter nodes.
